### PR TITLE
Fixing the fading animation when the current slide switches to the next slide

### PR DESCRIPTION
**Pull request by bchhun**
fixes issue #10

### CODE REVIEW

**Comment by akrabat** [comment]
That's great :)

**Comment by bchhun** [comment]
Does it shows that I'm working on a presentation with the avalanche theme ? Might as well fix some issues while on it :)

**Comment by akrabat** [comment]
I appreciate it :)

**Comment by nashamri** [comment]
Thanks @bchhun :+1:

**Pull request merged**
